parameters:

services:    
    busline_service:
        class: Telosys\Domain\Service\BusLineService
        arguments: ['@busline_repository', '@logger', '@rennes_metropole_open_data_repository', '@bus_line_stops_coordinates_repository']
        
    busline_repository:
        class: AppBundle\Repository\BusLineRepository
        factory : ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle:BusLine']
        
    rennes_metropole_open_data_repository:
        class: AppBundle\Repository\RennesMetropoleOpenDataRepository
        arguments: ['@rennes_metropole_api_request']
        
    rennes_metropole_api_request:
        class: Component\ApiComponent\RennesMetropoleApiRequest
        arguments: ['%api_end_point%']
        
    bus_line_stops_coordinates_repository:
        class: AppBundle\Repository\BusLineStopsCoordinatesRepository
        factory: ['@doctrine_mongodb', getRepository]
        arguments: ["AppBundle:BusLineStopsCoordinates"]
